use_frameworks!

target 'NaruiMapKit_Example' do
  pod 'NaruiMapKit', :path => '../'

  target 'NaruiMapKit_Tests' do
    inherit! :search_paths

    pod 'Alamofire'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
  end
end
